### ISSUE TITLE
startActivityForResult 랑 다른거 하나 deprecated 되엇는데... ㅎㅎ 

### ISSUE THREAD

**Issue by kwon-Doosan** [Fastcampus-Android-Lecture-Project-2021/aop-part2-chapter05#1]
https://github.com/Fastcampus-Android-Lecture-Project-2021/aop-part2-chapter05/blob/413b80254732a2eb618a3278c1c1eb90635521a7/app/src/main/java/fastcampus/aop/part2/chapter05_final/MainActivity.kt#L102

**Comment by kyeongwan** [comment]
안녕하세요 @kwon-Doosan 님!
예제에서는 androidx.activity 는 사용되지 않았습니다.

감사합니다.

**Comment by kwon-Doosan** [comment]
아아 제말은 androidx에서는 어떻게 대응해야할지 알려주시면 좋겟다이겁니다 ㅠ ㅎㅎ

2021년 5월 28일 (금) 오전 1:49, Kyeongwan Lucas Kang ***@***.***>님이
작성:

**Comment by kwon-Doosan** [comment]
걍 문서보니까 쉽네요 ㅎㅎ 신경안쓰셔도 될것같습니다 ㅎ

2021년 5월 28일 (금) 오전 11:54, Soonsung Kwon ***@***.***>님이 작성:
